file(MAKE_DIRECTORY "${OUTPUT}")
execute_process(COMMAND "${CROSS}" compile "${EXAMPLES}/factorial.cross" --out "${OUTPUT}/program.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "compile failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${OUTPUT}/program.cross-image" --steps 30 --save "${OUTPUT}/checkpoint.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 1 OR NOT text MATCHES "STEP_BUDGET")
  message(FATAL_ERROR "partial run failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${OUTPUT}/checkpoint.cross-image" --policy reverse --save "${OUTPUT}/complete.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "\"value\":720")
  message(FATAL_ERROR "fresh process resume failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" export "${OUTPUT}/complete.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "720")
  message(FATAL_ERROR "export failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${EXAMPLES}/faces-edges-vertices.cross" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "\"value\":360")
  message(FATAL_ERROR "structural language failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${EXAMPLES}/meaning.cross" --meaning "${EXAMPLES}/../stdlib/meaning.cross" --save "${OUTPUT}/meaning.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "\"value\":400")
  message(FATAL_ERROR "semantic pattern library failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${OUTPUT}/meaning.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "\"value\":400")
  message(FATAL_ERROR "persisted semantic image failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${EXAMPLES}/rule90.cross" --meaning "${EXAMPLES}/../stdlib/structure.cross" --input "${EXAMPLES}/rule90.json" --memory compact --steps 500 --save "${OUTPUT}/compact.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 1 OR NOT text MATCHES "STEP_BUDGET")
  message(FATAL_ERROR "compact partial run failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${OUTPUT}/compact.cross-image" --memory compact --steps 20000 --save "${OUTPUT}/compact-done.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "\"value\":\\[true,false,true,false,true,false,true\\]")
  message(FATAL_ERROR "compact fresh process resume failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" inspect "${OUTPUT}/compact-done.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "\"history\":\\[\\]")
  message(FATAL_ERROR "compact history policy failed: ${text}")
endif()
# Both meaning files must be loaded. The generated field graph is persisted,
# then resumed without the original source files in the new process.
execute_process(COMMAND "${CROSS}" run "${EXAMPLES}/grid-stencil.cross" --meaning "${EXAMPLES}/../stdlib/structure.cross" --meaning "${EXAMPLES}/../stdlib/grid.cross" --input "${EXAMPLES}/grid-stencil.json" --memory compact --steps 110 --save "${OUTPUT}/grid-partial.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 1 OR NOT text MATCHES "STEP_BUDGET")
  message(FATAL_ERROR "grid partial run failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${OUTPUT}/grid-partial.cross-image" --scheduler scan --policy reverse --memory compact --steps 20000 --save "${OUTPUT}/grid-done.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "\"value\":\\[15,26,17,18,23,20\\]")
  message(FATAL_ERROR "grid process resume failed: ${text}")
endif()

# The image contains a completed prefix and an in-flight chunk. Resume in a
# fresh process with different selection and scheduler, without source files.
execute_process(COMMAND "${CROSS}" run "${EXAMPLES}/grid-window.cross" --meaning "${EXAMPLES}/../stdlib/structure.cross" --meaning "${EXAMPLES}/../stdlib/grid.cross" --input "${EXAMPLES}/grid-window.json" --memory compact --steps 200 --save "${OUTPUT}/chunks-partial.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 1 OR NOT text MATCHES "STEP_BUDGET" OR NOT text MATCHES "\"grid_chunks\":3")
  message(FATAL_ERROR "chunk partial run failed: ${text}")
endif()
execute_process(COMMAND "${CROSS}" inspect "${OUTPUT}/chunks-partial.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "格子の進行" OR NOT text MATCHES "\"history\":\\[\\]")
  message(FATAL_ERROR "chunk progress was not persisted: ${text}")
endif()
execute_process(COMMAND "${CROSS}" run "${OUTPUT}/chunks-partial.cross-image" --scheduler scan --policy reverse --memory compact --steps 20000 --save "${OUTPUT}/chunks-done.cross-image" RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "\"value\":\\[15,26,17,18,23,20\\]")
  message(FATAL_ERROR "chunk process resume failed: ${text}")
endif()
